### ISSUE TITLE
[CONFORMANCE] Add Conformance for "same priority ANPs"; disjoint

### ISSUE THREAD

**Issue by tssurya** [kubernetes-sigs/network-policy-api#223]
**What existing test case does this issue concern**:

**What test case(s) would you like to be added**:

1. We need to add conformance tests for same priority admin network policies that are disjoint with their rules such that both should work as expected

**Why this is needed**:

1. See https://github.com/kubernetes-sigs/network-policy-api/issues/216

FYI: We don't plan to tackle tests for the don't work as expected bits

**Comment by vpbh** [comment]
I'm interested in picking this up — sharing a quick strategy first to confirm direction before I assign myself.

Since this predates `NPEP-285`, I'd implement it against Admin-tier `ClusterNetworkPolicy` (`v1alpha2`), consistent with the rest of the rewritten suite. 
Plan: a new `CNPAdminTierSamePriorityDisjoint` test + manifest with two priority-50 Admin CNPs sharing one subject (`gryffindor`) but disjoint ingress peers (`slytherin`, `hufflepuff`), asserting both Deny rules are enforced simultaneously — plus a control (`ravenclaw` → `gryffindor` allowed) to confirm neither over-applies. That directly exercises the non-conformant case from [#216](https://github.com/kubernetes-sigs/network-policy-api/issues/216) where only the first same-priority policy takes effect.

Two things I'd like your call on before I start:
 - Disjointness via different peers (above), or would you also want disjoint subjects and/or a disjoint direction (one ingress / one egress) case?
 - Admin-tier only, or also a `CNPBaselineTier*` sibling now that Baseline has priorities?

**Comment by npinaeva** [comment]
the plan sounds good, I would say both Baseline and Admin tier could you this test. For the configs same subject, different peers and different subjects same peer would be the most common cases to test
