### ISSUE TITLE
[CONFORMANCE] Run network policy tests here in network-policy-api project

### ISSUE THREAD

**Issue by tssurya** [kubernetes-sigs/network-policy-api#226]
**Why this is needed**:

Network policy project should be invovled in net-pol CI flakes and issues. @aojea mentioned this was broken for over a month and we didn't know about it

We need to run net-pol tests here so that we are more involved in this.

**Comment by aojea** [comment]
I rather prefer to centralize instead of spread it, we have a testgrid for sig network that I'm maintaining alone https://testgrid.k8s.io/sig-network-gce,  and we have one presubmit https://testgrid.k8s.io/sig-network-gce#presubmit-network-policies,%20google-gce that runs for PR that change network policy related code and one periodic https://testgrid.k8s.io/sig-network-gce#network-policies,%20google-gce

**Comment by aojea** [comment]
oh, I think I misunderstood, do you mean to move the existing jobs to this testgrid tab https://testgrid.k8s.io/sig-network-policy-api ?

that will be awesome

**Comment by tssurya** [comment]
yes exactly so having all the network policies run in one place (which right now I don't mind if its centralized) but my goal was to have this group handle some of that maintenance work and help you out. Right now the problem is we didn't even know where to look, so thank you for the links.

I think its nice to move those jobs to the sig-network-policy-api grid yes and then in our bi-weekly meetings we should have some light purview on these jobs and ensure they are green

**Comment by tssurya** [comment]
seems like this is done: https://testgrid.k8s.io/sig-network-policy-api
