### ISSUE TITLE
Add conformance tests for the AdminNetworkPolicy API 

### ISSUE THREAD

**Issue by astoycos** [kubernetes-sigs/network-policy-api#35]
Now that the API has physically merged https://github.com/kubernetes-sigs/network-policy-api/pull/30 We should look at adding conformance testing, cyclonus already does this for netpol so it seems to make sense to extend the tool for the AdminNetworkPolicy API as well.

**Comment by astoycos** [comment]
I would ensure #34 Is completed before tackling this.

**Comment by olivercodes** [comment]
Hey @abhijit-dev82 do you think you'll have time for this one? If not I'd love to jump on it, but no worries either way!

**Comment by abhijit-dev82** [comment]
hey Sorry for the late reply. Please go ahead, have too many things on my hand for now.

**Comment by olivercodes** [comment]
> hey Sorry for the late reply. Please go ahead, have too many things on my hand for now.

@abhijit-dev82 Hey no problem, life happens!

**Comment by mattfenwick** [comment]
Assuming this will be tackled using Cyclonus, I suggest something like:

1. extend Cyclonus engine to support ANP and BANP
   - priority levels for policies
   - cluster-level policies (currently: cyclonus forces everything to have a namespace)
     - does isolation work differently for ANP?  this says so: https://github.com/kubernetes-sigs/network-policy-api/blob/master/site-src/guides/api-overview.md#general-notes
   - pass
   - deny
 
2. add interesting test cases for network policies -- some ideas:
   - ANP by themselves
   - BANP by themselves
   - ANP + standard NP + BANP

3. end-user utilities
   - linting
   - pretty printing

**Comment by olivercodes** [comment]
For those unaware, we also did a cyclonus deep dive today on Antrea Live (youtube):
https://www.youtube.com/watch?v=iuurc8852mE

**Comment by mattfenwick** [comment]
Links:

 - [struct defs](https://github.com/kubernetes-sigs/network-policy-api/tree/master/apis/v1alpha1)
 - [docs](https://github.com/kubernetes-sigs/network-policy-api/tree/master/site-src/guides)
 - [KEP issue](https://github.com/kubernetes/enhancements/issues/2091)
 - [actual KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2091-admin-network-policy)

**Comment by astoycos** [comment]
[Pending Update to KEP](https://github.com/kubernetes/enhancements/pull/3660) :)

**Comment by mattfenwick** [comment]
@olivercodes I read through the ANP KEP and examples -- I wrote down [my understanding in my comment above ^^^](https://github.com/kubernetes-sigs/network-policy-api/issues/35#issuecomment-1325205067), along with a few questions about areas that I'm uncertain on.

Lmk if you have some time for us to collab on tracking down answers to these question, this will help us put together a high-level pseudo-code algorithm!  

I think creating a small set of concrete examples -- especially ones that include combinations of ANP/k8s/BANP netpols -- will guide our work.  Aside from the KEP, do we have a collection of those anywhere?

**Comment by tssurya** [comment]
/assign @tssurya {Since there hasn't been much progress here + I am starting on doing end-to-end testing for [my downstream implementation with OVN-Kubernetes](https://github.com/ovn-org/ovn-kubernetes/pull/3489) plugin.} @olivercodes hope you are fine with this...

This is an issue gating our move to Beta. As discussed in the recent past sig-network-policy-api meetings I am willing to take over this issue and work on it to be more generic so that all plugins can use it. I will be mimicing what the `gateway-api` folks are doing for conformance: https://github.com/kubernetes-sigs/gateway-api/pull/1967

The thoughts I had were very similar to https://github.com/kubernetes-sigs/network-policy-api/issues/35#issuecomment-1325205067 - the only caveat I have is I am not sure if the first iteration will contain the cyclonus support for this since I don't have that kind of time, however I will start with the conformance test framework and write the actual tests and their pipeline results will be fed into the gateway API style CRDs to show what passes and what fails.

I would suggest we track the cyclonus tool support for ANP/BANP and updates to that under https://github.com/kubernetes-sigs/network-policy-api/issues/69 that @olivercodes is working on.

@olivercodes , @mattfenwick @astoycos I hope that is ok! I don't want to delay conformance testing and couple that with cyclonus for now. I can first get the test suite ready to go and the latter part of integrating that with cyclonus can be done later IMHO like as spoke the other day @astoycos!

**Comment by mattfenwick** [comment]
> I would suggest we track the cyclonus tool support for ANP/BANP and updates to that under #69 that @olivercodes is working on.
> 
> @olivercodes , @mattfenwick @astoycos I hope that is ok! I don't want to delay conformance testing and couple that with cyclonus for now. I can first get the test suite ready to go and the latter part of integrating that with cyclonus can be done later IMHO like as spoke the other day @astoycos!

+1 @tssurya , I'm on board with this approach !  I honestly think the test suite you're putting together will make the eventual cyclonus work easier when it does happen , so no matter how we look at it, what you're doing will be very helpful!
