### ISSUE TITLE
we don't need Same / NotSame for namespaces

### ISSUE THREAD

**Issue by danwinship** [kubernetes-sigs/network-policy-api#45]
We don't actually need Same / NotSame for namespaces, you can just specify `SameLabels: ["kubernetes.io/metadata.name"]` / `NotSameLabels: ["kubernetes.io/metadata.name"]` ...

**Comment by tssurya** [comment]
@danwinship @astoycos : So this part has been a bit confusing for me as I start to look deeper, I am sure I must be missing some KEP history, so please bear with me.

When I look at https://github.com/kubernetes-sigs/network-policy-api/blob/823a0d13a5afc566f19997db6a957de3de92c728/apis/v1alpha1/shared_types.go#L127 I can see that we have `Related`, `NamespaceSelector`, `SameLabels` & `NotSameLabels`  as ways for us to select a namespacedPeer.

```
type NamespacedPeer struct {
	// Related provides a mechanism for selecting namespaces relative to the
	// subject pod. A value of "Self" matches the subject pod's namespace,
	// while a value of "NotSelf" matches namespaces other than the subject
	// pod's namespace.
	// +optional
	Related *NamespaceRelation `json:"related,omitempty"`

	// NamespaceSelector is a labelSelector used to select Namespaces, This field
	// follows standard label selector semantics; if present but empty, it selects
	// all Namespaces.
	// +optional
	NamespaceSelector *metav1.LabelSelector `json:"namespaceSelector,omitempty"`

	// SameLabels is used to select a set of Namespaces that share the same values
	// for a set of labels.
	// To be selected a Namespace must have all of the labels defined in SameLabels,
	// and they must all have the same value as the subject of this policy.
	// If Samelabels is Empty then nothing is selected.
	// +optional
	// +kubebuilder:validation:MaxItems=100
	SameLabels []string `json:"sameLabels,omitempty"`

	// NotSameLabels is used to select a set of Namespaces that do not have a set
	// of label(s). To be selected a Namespace must have none of the labels defined
	// in NotSameLabels. If NotSameLabels is empty then nothing is selected.
	// +optional
	// +kubebuilder:validation:MaxItems=100
	NotSameLabels []string `json:"notSameLabels,omitempty"`
}
```

When we have a namespace selector already aren't the sameLabels and notSameLabels kind of overlapping with it?

Coming back to the original issue @danwinship : I guess what you meant is we don't need the `Related` field here since `Self` OR `NotSelf` can be represented via SameLabels OR NotSameLabels  - that makes sense to me. @astoycos : WDYT? I can do a PR for this one if you don't have concerns.

side-note: Do we need to to update the explanation for `sameLabels`?
Instead of:
```
	// SameLabels is used to select a set of Namespaces that share the same values
	// for a set of labels.
	// To be selected a Namespace must have all of the labels defined in SameLabels,
	// and they must all have the same value as the subject of this policy.
```

can we just have 

```
        // SameLabels is used to select a set of Namespaces that have the same set of labels
	// To be selected a Namespace must have all of the labels defined in SameLabels,
	// and they must all have the same value as the subject of this policy.

```
The word "values" makes it a bit confusing since it can be mistaken to be "same values for a set of labels" as in the value part of the key:value should be the same....that's what I thought initially.

**Comment by danwinship** [comment]
> When we have a namespace selector already aren't the sameLabels and notSameLabels kind of overlapping with it?

No, the namespace selector is for specifying "label has a specific value" (eg, "`isSystemNamespace: true`"), while same/notSameLabels is for specifying "label has the same/different value as it has in the reference namespace" (eg, same/different "`tenantName`" value as the namespace the policy is in).

> I guess what you meant is we don't need the `Related` field here since `Self` OR `NotSelf` can be represented via SameLabels OR NotSameLabels

Oh, hm, I forgot that we had switched from `Same`/`NotSame` to `Related`... actually, I had suggested `Related` because it potentially works well with the hierarchical namespaces idea that has been proposed for multi-tenant. (ie, in the future we could have `related: Parent` or `related: Child`). So maybe my idea here doesn't make sense...

**Comment by tssurya** [comment]
> > When we have a namespace selector already aren't the sameLabels and notSameLabels kind of overlapping with it?
> 
> No, the namespace selector is for specifying "label has a specific value" (eg, "`isSystemNamespace: true`"), while same/notSameLabels is for specifying "label has the same/different value as it has in the reference namespace" (eg, same/different "`tenantName`" value as the namespace the target pod is in).

yeah ACK, I can see that the latter provides a bit more freedom to express labels in a _relational fashion to its own labels_. gotcha!

I was thinking more like we could express the same/notsame match via namespaceSelectors like we could say tenantName: "foo" and that would give us everything that matches it but then we'd have to specially specify the "foo" value we want (whole label match) versus with sameLabels we don't care since we can simply give the key we want and it will take care of the rest for us.

> 
> > I guess what you meant is we don't need the `Related` field here since `Self` OR `NotSelf` can be represented via SameLabels OR NotSameLabels
> 
> Oh, hm, I forgot that we had switched from `Same`/`NotSame` to `Related`... actually, I had suggested `Related` because it potentially works well with the hierarchical namespaces idea that has been proposed for multi-tenant. (ie, in the future we could have `related: Parent` or `related: Child`). 

hmm that's interesting.. I lack background on this, but even then self/NotSelf seems unnecessary as of now? More profound relations like what you mentioned above for hierarchical namespaces makes sense..

> So maybe my idea here doesn't make sense...

I still think you do raise a valid point around if `Self` and `NotSelf` are needed. We should probably see if this has use cases or adds more value..

**Comment by tssurya** [comment]
Forgot to leave an update on the consensus we took. This was discussed, and we are going to remove the relation pieces from alpha version of the API because currently the same thing for a isSelf namespace or not can be expressed using `sameLabels` and `nodeSameLabels` in this manner:

`Self`: `SameLabels: ["kubernetes.io/metadata.name"]`
`NotSelf`: `NotSameLabels: ["kubernetes.io/metadata.name"]`

We will for now remove these:

```
	// Related provides a mechanism for selecting namespaces relative to the
	// subject pod. A value of "Self" matches the subject pod's namespace,
	// while a value of "NotSelf" matches namespaces other than the subject
	// pod's namespace.
	// +optional
	Related *NamespaceRelation `json:"related,omitempty"`
```
and 

```
type NamespaceRelation string

const (
	NamespaceSelf    NamespaceRelation = "Self"
	NamespaceNotSelf NamespaceRelation = "NotSelf"
)
```

See @danwinship 's comment here: https://github.com/kubernetes-sigs/network-policy-api/issues/45#issuecomment-1276152364 on why we added the self and notself in the first place. However I think we can revisit this and expand the API more in betav1 and above when we have valid use cases. So far we haven't seen any special requests in this area.
